# Generated by Django 4.2.26 on 2026-01-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
    ]
