# Generated by Django 5.2.10 on 2026-02-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_priority'),
    ]

    operations = [
    ]
