# Generated by Django 5.2.10 on 2026-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20260216_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='review_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
