# Generated by Django 5.2.10 on 2026-03-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_usertask_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='review_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20),
        ),
    ]
