# Generated by Django 5.2.10 on 2026-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_usertask_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
