# Generated by Django 6.0.2 on 2026-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_category_task_category_categorymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('registry', 'Registry'), ('business_development', 'Business Development'), ('innovation_consultancy', 'Innovation and Consultancy Services'), ('construction_engineering', 'Construction and Engineering'), ('legal_services', 'Legal Services'), ('investment', 'Investment'), ('joint_venture', 'Joint Venture'), ('internal_audit', 'Internal Audit'), ('finance_accounting', 'Finance and Accounting Management'), ('procurement', 'Procurement Management'), ('administration', 'Administration'), ('public_affairs', 'Public Affairs and Information'), ('ict', 'Information, Communication and Technology'), ('property_management', 'Property Management'), ('human_resource', 'Human Resource Management')], max_length=100),
        ),
    ]
