# Generated by Django 6.0.2 on 2026-03-25 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_category_created_by_alter_category_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(related_name='categories', through='tasks.CategoryMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorymember',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_members', to='tasks.category'),
        ),
    ]
