# Generated by Django 6.0.2 on 2026-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_taskreportrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_review', 'Task Review'), ('task_due_soon', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('task_updated', 'Task Updated'), ('task_accepted', 'Task Accepted'), ('task_rejected', 'Task Rejected'), ('task_reassigned', 'Task Reassigned'), ('assigned_task_overdue', 'Assigned Task Overdue'), ('task_review_delay', 'Task Review Delay')], max_length=30),
        ),
    ]
