# Generated by Django 6.0.2 on 2026-04-03 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('morning_focus', models.TextField(blank=True)),
                ('progress_update', models.TextField(blank=True)),
                ('end_of_day_summary', models.TextField(blank=True)),
                ('tomorrow_plan', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='daily_checkins/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('priority_tasks', models.ManyToManyField(blank=True, related_name='daily_checkins', to='tasks.usertask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_daily_checkin_per_user_date')],
            },
        ),
    ]
