# Generated by Django 4.2.26 on 2026-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_category_created_by_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='in_progress', max_length=20),
        ),
    ]
