# Generated by Django 4.2.26 on 2026-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_activitycategory_task_activity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='section',
            field=models.CharField(choices=[('registry', 'Registry'), ('business_development', 'Business Development'), ('innovation_consultancy', 'Innovation and Consultancy Services'), ('construction_engineering', 'Construction and Engineering'), ('legal_services', 'Legal Services'), ('investment', 'Investment'), ('joint_venture', 'Joint Venture'), ('internal_audit', 'Internal Audit'), ('finance_accounting', 'Finance and Accounting Management'), ('procurement', 'Procurement Management'), ('administration', 'Administration'), ('public_affairs', 'Public Affairs and Information'), ('ict', 'Information, Communication and Technology'), ('property_management', 'Property Management'), ('human_resource', 'Human Resource Management')], max_length=100),
        ),
    ]
